############################################################################
# apps/examples/gt9271_touch_test/Makefile
#
# GT9271 LCD IIC Touchscreen Test Application Makefile
#
############################################################################

include $(APPDIR)/Make.defs

# GT9271 Touch Test Application

PROGNAME = $(CONFIG_EXAMPLES_GT9271_TOUCH_TEST_PROGNAME)
PRIORITY = $(CONFIG_EXAMPLES_GT9271_TOUCH_TEST_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_GT9271_TOUCH_TEST_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_GT9271_TOUCH_TEST)

MAINSRC = gt9271_touch_test_main.c

include $(APPDIR)/Application.mk
